### PR TITLE
PythonCode

### PR DESCRIPTION
**Pull request by nikhitmago**
Python Code

### CODE REVIEW

**Comment by chitragautam** [comment]
Hello,
Can youplease provide us your datafile "processed_los_angeles_aqi_14_months.csv". we want to see the format of that dataformat and want to run your program.

Thanks and regards

**Comment by nikhitmago** [comment]
Hey,

I cannot give the data since this was part of a research project!

Regards,

Nikhit Mago

**Comment by chitragautam** [comment]
ok

**Comment by chitragautam** [comment]
Ok....but can you please help us to format data....how you have formatted
your data

**Comment by chitragautam** [comment]
Hello Nikhit,

Please help me to arrange metrology data in Air quality project. As we find
some sample data of air quality thanks for that. Please help us to arrange
metrological data format and send me some sample data format so that I can
arrange my data. Further we'll surely acknowledge you for your help.

Thanks & Regards
Chitra Gautam

**Comment by nikhitmago** [comment]
Sure, I’ll do that. I’m working on project right now but I’ll send you as soon as I get some time.

**Comment by chitragautam** [comment]
Thank you very much Nikhit....please send us format of metrological data so
that it'll be easy for us to arrange our data.

Thanks & Regards
Chitra Gautam

**Comment by chitragautam** [comment]
Hello Nikhit,

Gud Morning

Please send me meteorological data format so that I can prepare mine. We
have stuck in-between n you can help. Please help us to resolve this
problem and sens us the sample meteorological data forma.
Waiting for you positive reply.

Thanks and regards,
Chitra Gautam

**Comment by nikhitmago** [comment]
Hello,

I am attaching the sample data in this email, hope it helps!

Which University/Institution do you belong to and how did you come across the GitHub repo?



Regards,

Nikhit Mago

**Comment by chitragautam** [comment]
Hello Nikhit,

Thanks for the response.
But there is no data attached with this mail. I request you to kindly
attach data file.


Thanks in advance
Regards,
Chitra Gautam

**Comment by nikhitmago** [comment]
Regards,

Nikhit Mago

**Comment by chitragautam** [comment]
Hello,
Can you plz send me data sample on my mail id coz still m not getting
metrological sample data from Ur this mail also. May be file is not
attached.

rajvirsgautam@gmail.com
Thanks & Regards
Chitra Gautam

**Pull request merged**
